# Build deps Layer:
#   sam build DuckDependenciesLayer
#
# Build everything:
#   sam build
#
# Local Run
#   sam local start-api --region us-west-2 --profile <profile>
#
# Deploy
#   sam deploy --stack-name=duck-stac --no-confirm-changeset --region us-west-2 --profile <profile>

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-duckdb-stac

Parameters:
  LambdaTimeout:
    Default: 30
    Description: 'Max lambda execution time in seconds'
    Type: Number
  LambdaMemorySize:
    Default: 2048
    Description: 'Max lambda Memory in Mb'
    Type: Number
  StacParquetLocations:
    Default: |
      {
        "glo-30-hand": "s3://asf-stac-duckdb/glo-30-hand.parquet",
        "sentinel-1-global-coherence": "s3://asf-stac-duckdb/sentinel-1-global-coherence.parquet"
      }
    Description: 'JSON Object pointing to collections Location of'
    Type: String
  StacBucketName:
    Description: 'Optional Bucket to grant lambda access to'
    Type: String
    Default: 'asf-stac-duckdb'
  CustomDomainName:
    Description: 'Custom Domain Name for API Gateway'
    Type: String
    Default: 'stac.sp.asf.alaska.edu'
  HostedZoneId:
    Type: String
    Default: ''
    Description: 'Optional Hosted Zone ID for Route53 (leave blank to skip custom domain setup)'

Conditions:
  IsS3: !Not [!Equals [!Ref StacBucketName, ""]]
  UseCustomDomain: !Not [!Equals [!Ref HostedZoneId, ""]]

Resources:
  DuckDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: duck-dependencies-layer
      Description: Python dependencies DuckStac functions
      ContentUri: ./
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  DuckStacFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_root/
      Handler: stac_fastapi.duckdb.app.handler
      Runtime: python3.11
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Layers:
        - !Ref DuckDependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAC_FILE_PATH: /var/task/data/stac_collections
          BACKEND: duckdb
          TZ: UTC             # Avoid Timezone Error
          HOME: "/tmp/"       # Otherwise DuckDB breaks
          PARQUET_URLS_JSON: !Ref StacParquetLocations
      Policies:
        - S3FullAccessPolicy:
            Condition: IsS3
            BucketName: !Ref StacBucketName
      Events:
        DuckStac:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExplicitApiHttpApi
            Path: /{proxy+}
            Method: ANY

 #
  ExplicitApiHttpApi:
    Type: AWS::Serverless::HttpApi

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref CustomDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomainName
          HostedZoneId: !Ref HostedZoneId

  ApiCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref CustomDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref ApiCertificate
          EndpointType: REGIONAL

  ApiDomainMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref ApiCustomDomain
      ApiId: !Ref ExplicitApiHttpApi
      Stage: '$default'

  ApiDnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: UseCustomDomain
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomDomainName
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !GetAtt ApiCustomDomain.RegionalDomainName

Outputs:
  DuckStacApi:
    Description: "API Gateway endpoint URL for Prod stage for DuckStac function"
    Value: !Sub "https://${ExplicitApiHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  CustomDomainUrl:
    Description: "Custom domain endpoint (only created when HostedZoneId parameter was provided)"
    Condition: UseCustomDomain
    Value: !Sub "https://${CustomDomainName}/"