# Build deps Layer:
#   sam build DuckDependenciesLayer
#
# Build everything:
#   sam build
#
# Local Run
#   sam local start-api --region us-west-2 --profile <profile>
#
# Deploy
#   sam deploy --stack-name=duck-stac --no-confirm-changeset --region us-west-2 --profile <profile>

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: serverless-duckdb-stac

Parameters:
  LambdaTimeout:
    Default: 30
    Description: 'Max lambda execution time in seconds'
    Type: Number
  LambdaMemorySize:
    Default: 2048
    Description: 'Max lambda Memory in Mb'
    Type: Number
  StacParquetLocations:
    Default: | #Changed from 'all_collections' to their specific stac collections for readability/accessability
            {
              "glo-30-hand": "s3://asf-stac-duckdb/glo-30-hand.parquet", 
              "sentinel-1-global-coherence": "s3://asf-stac-duckdb/sentinel-1-global-coherence.parquet"
            }
#            {
#              "glo-30-hand": "/var/task/data/parquet_files/all_collections.parquet",
#              "sentinel-1-global-coherence": "/var/task/data/parquet_files/all_collections.parquet"
#            }
    Description: 'JSON Object pointing to collections Location of'
    Type: String
  StacBucketName:
    Description: 'Optional Bucket to grant lambda access to'
    Type: String
    Default: 'asf-stac-duckdb'
  
  CustomDomainName:
    Description: 'Custom Domain Name for API Gateway'
    Type: String
    Default: 'stac.sp.asf.alaska.edu'
  HostedZoneId: 
    Type: String
    Default: ''
    Description: 'Optional Hosted Zone ID for Route53'

Conditions:
  IsS3: !Not [!Equals [!Ref StacBucketName, ""]]
  UseCustomDomain: !Not [!Equals [!Ref HostedZoneId, ""]] #this

Resources:
  DuckDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: duck-dependencies-layer
      Description: Python dependencies DuckStac functions
      ContentUri: ./
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.11

  DuckStacFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_root/
      Handler: stac_fastapi.duckdb.app.handler
      Runtime: python3.11
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Layers:
        - !Ref DuckDependenciesLayer
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAC_FILE_PATH: /var/task/data/stac_collections
          BACKEND: duckdb
          TZ: UTC             # Avoid Timezone Error
          HOME: "/tmp/"       # Otherwise DuckDB breaks
          PARQUET_URLS_JSON: !Ref StacParquetLocations
      Policies:
        - S3FullAccessPolicy:
            Condition: IsS3
            BucketName: !Ref StacBucketName
      Events:
        DuckStac:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref ExplicitApiHttpApi
            Path: /{proxy+}
            Method: ANY



# More information: https://cruisemaniac.com/posts/sam-cli-custom-domains-route53/
# Domain is passed in when its deployed, HostedZoneId is passed in when its deployed, and the certificate is created automatically by SAM.



# If the custom domain is used the custom domain name is created, and we create the api cert.
# after the certificate is created, its passed in
# if no custom domain is used the api is created with no certificate, and the default api endpoint is used
  ExplicitApiHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain: !If
        - UseCustomDomain
        - DomainName: !Ref CustomDomainName
          CertificateArn: !Ref ApiCertificate
        - Route53:
            HostedZoneId: !Ref HostedZoneId
        - !Ref "AWS::NoValue"

# Needs custom domain name to be created, we pass it in to the certificate, and then the certificate is passed in to the api.
# USe the stac.sp domain name, as well as the hosted zone id for the certificate to be created.
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: UseCustomDomain
    Properties:
      DomainName: !Ref CustomDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  DuckStacApi:
    Description: "API Gateway endpoint URL for Prod stage for DuckStac function"
    Value: !Sub "https://${CustomDomainName}/"
  CustomDomainUrl:
    Description: Custom endpoint for API
    Condition: UseCustomDomain
    Value: !Sub "https://${CustomDomainName}/"
#template
