name: workflow ingestion
on:
  workflow_dispatch:
    inputs:
      collection:
        description: 'Collection name'
        required: true
        type: string
permissions:
  id-token: write
  contents: write

env:
  DATA_BUCKET: asf-stac-duckdb
  DATA_REGION: us-west-2
  DATA_PIPELINE_ROLE: arn:aws:iam::577391712883:role/aws-sam-cli-managed-asf-stac--PipelineExecutionRole-ESPP2g3IJ3tl

jobs:
  ingest-and-convert:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal:ubuntu-full-latest
    steps:
      - name: install git/make/python
        run: |
          apt-get update
          apt-get install -y git make python3.9 python3.9-venv python3-pip
      
      - uses: actions/checkout@v3

      - name: run ingestion and conversion
        run: |
          make ingest COLLECTION=${{ github.event.inputs.collection }}