name: push test

on:
  push:
    paths:
      - '/duck-stac/lambda_root/data/stac_colelctions/sentinel-1-global-coherence/coherence-s3-objects.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests for changed .txt files"
  
